server:
  port: 8061
spring:
  application:
    name: sentinel-order
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8858
      web‐context‐unify: false # 默认将调用链路收敛
      datasource:
        sentinel-order-flow-rule:
          nacos:
            server-addr: 124.220.187.253:8848
            username: nacos
            password: nacos
            data-id: sentinel-order-flow-rule
            namespace: dev
            group-id: learn
            rule-type: flow