server:
  port: 8031
spring:
  application:
    name: nacos-order-loadbalancer
  cloud:
    nacos:
      server-addr: 124.220.187.253:8848
      discovery:
        username: nacos
        password: nacos
        namespace: dev
        group: learn
    loadbalancer:
      ribbon:
        enabled: false