server:
  port: 9527
spring:
  application:
    name: rabbitmq-provider
  rabbitmq:
    host: 120.26.68.86
    port: 5672
    #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)
    publisher-returns: true