server:
  port: 8021
spring:
  application:
    name: nacos-stock
  cloud:
    nacos:
      server-addr: 124.220.187.253:8848
      discovery:
        username: nacos
        password: nacos
        namespace: dev
        group: learn