server:
  port: 8023
spring:
  datasource:
    url: jdbc:mysql://120.26.68.86:3306/goods
    username: root
    password: Scy962464.
  application:
    name: nacos-product
  cloud:
    nacos:
      server-addr: 124.220.187.253:8848
      discovery:
        username: nacos
        password: nacos
        namespace: dev
        group: learn
#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lemon.learn.model
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true